server:
  port: 9090
spring:
  main:
    allow-circular-references: true
  application:
    name: school-web
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

